import img from '../../assets/index';
import uniqid from 'uniqid';

const characters = [
  { name: 'Charlie Kelly', img: img.charlie, id: uniqid() },
  { name: "Ronald 'Mac' Macdonald", img: img.mac, id: uniqid() },
  { name: 'Dee Reynolds', img: img.dee, id: uniqid() },
  { name: 'Denis Reynolds', img: img.dennis, id: uniqid() },
  { name: 'Frank Reynolds', img: img.frank, id: uniqid() },
  { name: 'Waitress', img: img.waitress, id: uniqid() },
  { name: 'Rickety Cricket', img: img.cricket, id: uniqid() },
  { name: 'Artemis', img: img.artemis, id: uniqid() },
  { name: 'Bonnie Kelly', img: img.bonnie, id: uniqid() },
  { name: 'Mrs. Mac', img: img.mrsMac, id: uniqid() },
  { name: 'Bill Ponderosa', img: img.bill, id: uniqid() },
  { name: 'Uncle Jack', img: img.uncleJack, id: uniqid() },
  { name: 'Luther Macdonald', img: img.luther, id: uniqid() },
  { name: 'Liam McPoyle', img: img.liam, id: uniqid() },
  { name: 'Ryan McPoyle', img: img.ryan, id: uniqid() },
  { name: 'Waiter', img: img.waiter, id: uniqid() },
  { name: 'Maureen Ponderosa', img: img.maureen, id: uniqid() },
  { name: 'Ben the Soldier', img: img.ben, id: uniqid() },
  { name: 'Rex', img: img.rex, id: uniqid() },
  { name: 'The Lawyer', img: img.lawyer, id: uniqid() },
  { name: 'Margaret McPoyle', img: img.margaret, id: uniqid() },
  { name: 'Z', img: img.z, id: uniqid() },
  { name: 'Carmen', img: img.carmen, id: uniqid() },
  { name: 'Barbara Reynolds', img: img.barbara, id: uniqid() },
  { name: 'Jackie Denardo', img: img.denardo, id: uniqid() },
  { name: 'Hwang', img: img.hwang, id: uniqid() },
  { name: 'Principal MacIntyre', img: img.principalMacIntyre, id: uniqid() },
  { name: 'Gail the Snail', img: img.gail, id: uniqid() },
  { name: 'Duncan', img: img.duncan, id: uniqid() },
  { name: 'Fatty Magoo', img: img.ingrid, id: uniqid() },
  { name: 'Don Cheadle', img: img.donCheadle, id: uniqid() },
  { name: 'Old Black Man', img: img.blackMan, id: uniqid() },
  { name: 'Pop-Pop', img: img.popPop, id: uniqid() },
  { name: 'Shelley Kelly', img: img.shelley, id: uniqid() },
  { name: 'Bruce Mathis', img: img.bruce, id: uniqid() },
  { name: 'Schmitty', img: img.schmitty, id: uniqid() },
  { name: 'Pepper Jack', img: img.pepperJack, id: uniqid() },
  { name: 'Juarez Family', img: img.juarezFamily, id: uniqid() },
  { name: "Lil' Kev", img: img.lilKev, id: uniqid() },
  { name: 'The Maniac', img: img.maniac, id: uniqid() },
  { name: 'Adriano Calvanese', img: img.adriano, id: uniqid() },
  { name: 'Gladys', img: img.gladys, id: uniqid() },
  { name: 'Pappy McPoyle', img: img.pappy, id: uniqid() },
  { name: 'Wade Boggs', img: img.wadeBoggs, id: uniqid() },
  { name: 'Boss Hogg', img: img.bossHogg, id: uniqid() },
  { name: 'Country Mac', img: img.countryMac, id: uniqid() },
  { name: 'Franquito', img: img.franquito, id: uniqid() },
  { name: 'Wally', img: img.wally, id: uniqid() },
  { name: 'Dave Drisco', img: img.drisco, id: uniqid() },
  { name: 'John Thundergun', img: img.thundergun, id: uniqid() },
  { name: 'Big Mo', img: img.bigMo, id: uniqid() },
  { name: 'Sinbad & Rob Thomas', img: img.sinbadRobThomas, id: uniqid() },
  { name: 'Psycho Pete', img: img.psychoPete, id: uniqid() },
];

export default characters;
