import img from '../../assets/index';

const characters = [
  { name: 'Charlie Kelly', img: img.charlie },
  { name: "Ronald 'Mac' Macdonald", img: img.mac },
  { name: 'Dee Reynolds', img: img.dee },
  { name: 'Denis Reynolds', img: img.dennis },
  { name: 'Frank Reynolds', img: img.frank },
  { name: 'Waitress', img: img.waitress },
  { name: "Rickety Cricket", img: img.cricket },
  { name: 'Artemis', img: img.artemis },
  { name: 'Bonnie Kelly', img: img.bonnie },
  { name: 'Mrs. Mac', img: img.mrsMac },
  { name: 'Bill Ponderosa', img: img.bill },
  { name: 'Uncle Jack', img: img.uncleJack },
  { name: 'Luther Macdonald', img: img.luther },
  { name: 'Liam McPoyle', img: img.liam },
  { name: 'Ryan McPoyle', img: img.ryan },
  { name: 'Waiter', img: img.waiter },
  { name: 'Maureen Ponderosa', img: img.maureen },
  { name: 'Ben the Soldier', img: img.ben },
  { name: 'Rex', img: img.rex },
  { name: 'The Lawyer', img: img.lawyer },
  { name: 'Margaret McPoyle', img: img.margaret },
  { name: 'Z', img: img.z },
  { name: 'Carmen', img: img.carmen },
  { name: 'Barbara Reynolds', img: img.barbara },
  { name: 'Jackie Denardo', img: img.denardo },
  { name: 'Hwang', img: img.hwang },
  { name: 'Principal MacIntyre', img: img.principalMacIntyre },
  { name: 'Gail the Snail', img: img.gail },
  { name: 'Duncan', img: img.duncan },
  { name: "Fatty Magoo", img: img.ingrid },
  { name: 'Don Cheadle', img: img.donCheadle },
  { name: 'Old Black Man', img: img.blackMan },
  { name: 'Pop-Pop', img: img.popPop },
  { name: 'Shelley Kelly', img: img.shelley },
  { name: 'Bruce Mathis', img: img.bruce },
  { name: 'Schmitty', img: img.schmitty },
  { name: 'Pepper Jack', img: img.pepperJack },
  { name: 'Juarez Family', img: img.juarezFamily },
  { name: "Lil' Kev", img: img.lilKev },
  { name: 'The Maniac', img: img.maniac },
  { name: 'Adriano Calvanese', img: img.adriano },
  { name: 'Gladys', img: img.gladys },
  { name: 'Pappy McPoyle', img: img.pappy },
  { name: 'Wade Boggs', img: img.wadeBoggs },
  { name: 'Boss Hogg', img: img.bossHogg },
  { name: 'Country Mac', img: img.countryMac },
  { name: 'Franquito', img: img.franquito },
  { name: 'Wally', img: img.wally },
  { name: 'Dave Drisco', img: img.drisco },
  { name: 'John Thundergun', img: img.thundergun },
  { name: 'Big Mo', img: img.bigMo },
  { name: 'Sinbad & Rob Thomas', img: img.sinbadRobThomas },
  { name: 'Psycho Pete', img: img.psychoPete },
];

export default characters;
